name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      plan_created: ${{ steps.plan.outcome }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Verify Google Authentication
        run: |
          echo "========== ACTIVE ACCOUNT =========="
          gcloud auth list

          echo ""
          echo "========== CURRENT PROJECT =========="
          gcloud config get-value project

          echo ""
          echo "========== ENABLED COMPUTE API =========="
          gcloud services list --enabled | grep compute || true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan

  terraform-apply:
    needs: terraform-plan

    runs-on: ubuntu-latest

    environment:
      name: production

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Verify Google Authentication
        run: |
          echo "========== ACTIVE ACCOUNT =========="
          gcloud auth list

          echo ""
          echo "========== CURRENT PROJECT =========="
          gcloud config get-value project

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan